// <auto-generated />
using System;
using DACS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250716034541_CreateCareerSuggestionsTable")]
    partial class CreateCareerSuggestionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACS.Models.CareerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerQuestionId");

                    b.ToTable("CareerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerQuestionId = 1,
                            Text = "Sáng tạo nội dung, thiết kế",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 2,
                            CareerQuestionId = 1,
                            Text = "Sửa chữa, vận hành máy móc",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 3,
                            CareerQuestionId = 1,
                            Text = "Giúp đỡ, lắng nghe người khác",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 4,
                            CareerQuestionId = 2,
                            Text = "Vẽ tranh, viết truyện, dựng video",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 5,
                            CareerQuestionId = 2,
                            Text = "Lắp ráp thiết bị, thử nghiệm kỹ thuật",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 6,
                            CareerQuestionId = 2,
                            Text = "Tổ chức sự kiện, hỗ trợ cộng đồng",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 7,
                            CareerQuestionId = 3,
                            Text = "Nghệ thuật, ngôn ngữ, tưởng tượng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 8,
                            CareerQuestionId = 3,
                            Text = "Tính toán, phân tích, logic",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 9,
                            CareerQuestionId = 3,
                            Text = "Giao tiếp, kết nối và chia sẻ",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 10,
                            CareerQuestionId = 4,
                            Text = "Tự do, linh hoạt, không gò bó",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 11,
                            CareerQuestionId = 4,
                            Text = "Kỹ luật, có hệ thống",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 12,
                            CareerQuestionId = 4,
                            Text = "Tập thể, có tính tương tác cao",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 13,
                            CareerQuestionId = 5,
                            Text = "Ý tưởng, định hướng sáng tạo",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 14,
                            CareerQuestionId = 5,
                            Text = "Xử lý kỹ thuật, kỹ năng cụ thể",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 15,
                            CareerQuestionId = 5,
                            Text = "Kết nối nhóm, tạo không khí",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 16,
                            CareerQuestionId = 6,
                            Text = "Văn, nghệ thuật",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 17,
                            CareerQuestionId = 6,
                            Text = "Toán, Tin học, Lý",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 18,
                            CareerQuestionId = 6,
                            Text = "Sử, Địa, Giáo dục công dân",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 19,
                            CareerQuestionId = 7,
                            Text = "Sáng tạo, bay bổng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 20,
                            CareerQuestionId = 7,
                            Text = "Chi tiết, chính xác",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 21,
                            CareerQuestionId = 7,
                            Text = "Thấu cảm, nhiệt tình",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 22,
                            CareerQuestionId = 8,
                            Text = "Tạo video/TikTok/Youtube",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 23,
                            CareerQuestionId = 8,
                            Text = "Xem công nghệ mới",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 24,
                            CareerQuestionId = 8,
                            Text = "Tham gia nhóm cộng đồng",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 25,
                            CareerQuestionId = 9,
                            Text = "Tác phẩm nghệ thuật, ý tưởng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 26,
                            CareerQuestionId = 9,
                            Text = "Giải pháp kỹ thuật, lập trình",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 27,
                            CareerQuestionId = 9,
                            Text = "Tác động tích cực đến người khác",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 28,
                            CareerQuestionId = 10,
                            Text = "Suy nghĩ sáng tạo, đưa ra ý tưởng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 29,
                            CareerQuestionId = 10,
                            Text = "Áp dụng công nghệ, phân tích",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 30,
                            CareerQuestionId = 10,
                            Text = "Trao đổi, hỏi ý kiến người khác",
                            Type = "Xã hội"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bạn thích làm việc kiểu nào?"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bạn yêu thích hoạt động nào nhất?"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bạn thường giỏi việc gì hơn?"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Bạn thích môi trường làm việc như thế nào?"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Khi làm việc nhóm, bạn thường đảm nhận vai trò gì?"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Môn học bạn thích nhất thời phổ thông là?"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Bạn đánh giá bản thân là người thế nào?"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Nếu có thời gian rảnh, bạn sẽ chọn làm gì?"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Bạn muốn được công nhận vì điều gì?"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Bạn thích giải quyết vấn đề bằng cách nào?"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedMajors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerSuggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerType = "Kỹ thuật",
                            Resources = "https://www.freecodecamp.org/, https://viblo.asia/, Sách 'Cấu trúc dữ liệu và giải thuật'",
                            SuggestedMajors = "Công nghệ thông tin, Kỹ thuật phần mềm, Cơ điện tử"
                        },
                        new
                        {
                            Id = 2,
                            CareerType = "Sáng tạo",
                            Resources = "https://www.canva.com/learn/, https://www.behance.net/, Sách 'Thiết kế ý tưởng sáng tạo'",
                            SuggestedMajors = "Thiết kế đồ họa, Kiến trúc, Truyền thông đa phương tiện"
                        },
                        new
                        {
                            Id = 3,
                            CareerType = "Xã hội",
                            Resources = "https://moet.gov.vn/, Sách 'Tâm lý học đại cương', https://www.edx.org/",
                            SuggestedMajors = "Luật, Quản trị nhân lực, Giáo dục học"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DominantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CareerTestResults");
                });

            modelBuilder.Entity("DACS.Models.ChatHistory", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("DACS.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DACS.Models.PersonalityTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalityTests");
                });

            modelBuilder.Entity("DACS.Models.Suggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("DACS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DACS.Models.CareerOption", b =>
                {
                    b.HasOne("DACS.Models.CareerQuestion", "CareerQuestion")
                        .WithMany("Options")
                        .HasForeignKey("CareerQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerQuestion");
                });

            modelBuilder.Entity("DACS.Models.CareerTestResult", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.ChatHistory", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.Feedback", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.PersonalityTest", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("PersonalityTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.Suggestion", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.CareerQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DACS.Models.User", b =>
                {
                    b.Navigation("ChatHistories");

                    b.Navigation("Feedbacks");

                    b.Navigation("PersonalityTests");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
