// <auto-generated />
using System;
using DACS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250819054215_AddFAQ")]
    partial class AddFAQ
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DACS.Models.BannedWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BannedWords");
                });

            modelBuilder.Entity("DACS.Models.CareerOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CareerQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CareerQuestionId");

                    b.ToTable("CareerOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerQuestionId = 1,
                            Text = "Sáng tạo nội dung, thiết kế",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 2,
                            CareerQuestionId = 1,
                            Text = "Sửa chữa, vận hành máy móc",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 3,
                            CareerQuestionId = 1,
                            Text = "Giúp đỡ, lắng nghe người khác",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 4,
                            CareerQuestionId = 2,
                            Text = "Vẽ tranh, viết truyện, dựng video",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 5,
                            CareerQuestionId = 2,
                            Text = "Lắp ráp thiết bị, thử nghiệm kỹ thuật",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 6,
                            CareerQuestionId = 2,
                            Text = "Tổ chức sự kiện, hỗ trợ cộng đồng",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 7,
                            CareerQuestionId = 3,
                            Text = "Nghệ thuật, ngôn ngữ, tưởng tượng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 8,
                            CareerQuestionId = 3,
                            Text = "Tính toán, phân tích, logic",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 9,
                            CareerQuestionId = 3,
                            Text = "Giao tiếp, kết nối và chia sẻ",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 10,
                            CareerQuestionId = 4,
                            Text = "Tự do, linh hoạt, không gò bó",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 11,
                            CareerQuestionId = 4,
                            Text = "Kỹ luật, có hệ thống",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 12,
                            CareerQuestionId = 4,
                            Text = "Tập thể, có tính tương tác cao",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 13,
                            CareerQuestionId = 5,
                            Text = "Ý tưởng, định hướng sáng tạo",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 14,
                            CareerQuestionId = 5,
                            Text = "Xử lý kỹ thuật, kỹ năng cụ thể",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 15,
                            CareerQuestionId = 5,
                            Text = "Kết nối nhóm, tạo không khí",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 16,
                            CareerQuestionId = 6,
                            Text = "Văn, nghệ thuật",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 17,
                            CareerQuestionId = 6,
                            Text = "Toán, Tin học, Lý",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 18,
                            CareerQuestionId = 6,
                            Text = "Sử, Địa, Giáo dục công dân",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 19,
                            CareerQuestionId = 7,
                            Text = "Sáng tạo, bay bổng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 20,
                            CareerQuestionId = 7,
                            Text = "Chi tiết, chính xác",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 21,
                            CareerQuestionId = 7,
                            Text = "Thấu cảm, nhiệt tình",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 22,
                            CareerQuestionId = 8,
                            Text = "Tạo video/TikTok/Youtube",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 23,
                            CareerQuestionId = 8,
                            Text = "Xem công nghệ mới",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 24,
                            CareerQuestionId = 8,
                            Text = "Tham gia nhóm cộng đồng",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 25,
                            CareerQuestionId = 9,
                            Text = "Tác phẩm nghệ thuật, ý tưởng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 26,
                            CareerQuestionId = 9,
                            Text = "Giải pháp kỹ thuật, lập trình",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 27,
                            CareerQuestionId = 9,
                            Text = "Tác động tích cực đến người khác",
                            Type = "Xã hội"
                        },
                        new
                        {
                            Id = 28,
                            CareerQuestionId = 10,
                            Text = "Suy nghĩ sáng tạo, đưa ra ý tưởng",
                            Type = "Sáng tạo"
                        },
                        new
                        {
                            Id = 29,
                            CareerQuestionId = 10,
                            Text = "Áp dụng công nghệ, phân tích",
                            Type = "Kỹ thuật"
                        },
                        new
                        {
                            Id = 30,
                            CareerQuestionId = 10,
                            Text = "Trao đổi, hỏi ý kiến người khác",
                            Type = "Xã hội"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Bạn thích làm việc kiểu nào?"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Bạn yêu thích hoạt động nào nhất?"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Bạn thường giỏi việc gì hơn?"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Bạn thích môi trường làm việc như thế nào?"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Khi làm việc nhóm, bạn thường đảm nhận vai trò gì?"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Môn học bạn thích nhất thời phổ thông là?"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Bạn đánh giá bản thân là người thế nào?"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Nếu có thời gian rảnh, bạn sẽ chọn làm gì?"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Bạn muốn được công nhận vì điều gì?"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Bạn thích giải quyết vấn đề bằng cách nào?"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resources")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedMajors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CareerSuggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CareerType = "Kỹ thuật",
                            Resources = "https://www.freecodecamp.org/, https://viblo.asia/, Sách 'Cấu trúc dữ liệu và giải thuật'",
                            SuggestedMajors = "Công nghệ thông tin, Kỹ thuật phần mềm, Cơ điện tử"
                        },
                        new
                        {
                            Id = 2,
                            CareerType = "Sáng tạo",
                            Resources = "https://www.canva.com/learn/, https://www.behance.net/, Sách 'Thiết kế ý tưởng sáng tạo'",
                            SuggestedMajors = "Thiết kế đồ họa, Kiến trúc, Truyền thông đa phương tiện"
                        },
                        new
                        {
                            Id = 3,
                            CareerType = "Xã hội",
                            Resources = "https://moet.gov.vn/, Sách 'Tâm lý học đại cương', https://www.edx.org/",
                            SuggestedMajors = "Luật, Quản trị nhân lực, Giáo dục học"
                        });
                });

            modelBuilder.Entity("DACS.Models.CareerTestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DominantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CareerTestResults");
                });

            modelBuilder.Entity("DACS.Models.ChatHistory", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatHistories");
                });

            modelBuilder.Entity("DACS.Models.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FAQs");
                });

            modelBuilder.Entity("DACS.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("DACS.Models.LearningPathStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearStage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LearningPathSteps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Học Toán rời rạc, Tin học đại cương, Cơ sở lập trình",
                            DominantType = "Kỹ thuật",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Học Cấu trúc dữ liệu, OOP, Cơ sở dữ liệu, mạng máy tính",
                            DominantType = "Kỹ thuật",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Học Lập trình Web, AI/ML cơ bản, Dự án phần mềm",
                            DominantType = "Kỹ thuật",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Thực tập, khóa luận tốt nghiệp, học DevOps, học nâng cao ngành",
                            DominantType = "Kỹ thuật",
                            YearStage = "Năm 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Học Toán cao cấp, Khoa học cơ bản, kỹ năng nghiên cứu",
                            DominantType = "Nghiên cứu",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Học thống kê, phân tích số liệu, viết báo cáo khoa học",
                            DominantType = "Nghiên cứu",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Tham gia nghiên cứu thực tế, hội thảo khoa học",
                            DominantType = "Nghiên cứu",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Viết đề tài nghiên cứu, tham gia lab, chuẩn bị học cao học",
                            DominantType = "Nghiên cứu",
                            YearStage = "Năm 4"
                        },
                        new
                        {
                            Id = 9,
                            Content = "Học mỹ thuật cơ bản, lý thuyết màu sắc, nhiếp ảnh cơ bản",
                            DominantType = "Nghệ thuật",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 10,
                            Content = "Học thiết kế đồ họa, làm dự án cá nhân sáng tạo",
                            DominantType = "Nghệ thuật",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 11,
                            Content = "Học dựng phim, thiết kế giao diện người dùng (UI/UX)",
                            DominantType = "Nghệ thuật",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 12,
                            Content = "Triển lãm cá nhân, làm portfolio, thực tập tại công ty thiết kế",
                            DominantType = "Nghệ thuật",
                            YearStage = "Năm 4"
                        },
                        new
                        {
                            Id = 13,
                            Content = "Học kỹ năng giao tiếp, tâm lý học, làm việc nhóm",
                            DominantType = "Xã hội",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 14,
                            Content = "Học quản lý giáo dục, tổ chức sự kiện, cố vấn học tập",
                            DominantType = "Xã hội",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 15,
                            Content = "Tham gia CLB, hướng dẫn viên, công tác xã hội",
                            DominantType = "Xã hội",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 16,
                            Content = "Thực tập tại các tổ chức xã hội, lên kế hoạch đào tạo",
                            DominantType = "Xã hội",
                            YearStage = "Năm 4"
                        },
                        new
                        {
                            Id = 17,
                            Content = "Học quản trị kinh doanh, tư duy phản biện, kỹ năng bán hàng",
                            DominantType = "Doanh nhân",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 18,
                            Content = "Học marketing, tài chính căn bản, quản lý dự án",
                            DominantType = "Doanh nhân",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 19,
                            Content = "Thực hành khởi nghiệp, pitching ý tưởng, quản trị nhân sự",
                            DominantType = "Doanh nhân",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Thực tập tại doanh nghiệp, triển khai dự án kinh doanh thật",
                            DominantType = "Doanh nhân",
                            YearStage = "Năm 4"
                        },
                        new
                        {
                            Id = 21,
                            Content = "Học tin học văn phòng, nguyên lý kế toán, hành chính căn bản",
                            DominantType = "Công sở",
                            YearStage = "Năm 1"
                        },
                        new
                        {
                            Id = 22,
                            Content = "Học kế toán tài chính, nghiệp vụ hành chính, quy trình văn thư",
                            DominantType = "Công sở",
                            YearStage = "Năm 2"
                        },
                        new
                        {
                            Id = 23,
                            Content = "Thực hành quản trị hồ sơ, kỹ năng viết văn bản hành chính",
                            DominantType = "Công sở",
                            YearStage = "Năm 3"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Thực tập tại văn phòng, học phần mềm quản lý công việc",
                            DominantType = "Công sở",
                            YearStage = "Năm 4"
                        });
                });

            modelBuilder.Entity("DACS.Models.PersonalityTest", b =>
                {
                    b.Property<int>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestId"));

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalityTests");
                });

            modelBuilder.Entity("DACS.Models.Suggestion", b =>
                {
                    b.Property<int>("SuggestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuggestionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SuggestionId");

                    b.HasIndex("UserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("DACS.Models.UniversitySuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DominantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UniversitySuggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DominantType = "Kỹ thuật",
                            Major = "Công nghệ thông tin",
                            UniversityName = "ĐH Bách Khoa TP.HCM",
                            Website = "https://hcmut.edu.vn"
                        },
                        new
                        {
                            Id = 2,
                            DominantType = "Kỹ thuật",
                            Major = "Kỹ thuật phần mềm",
                            UniversityName = "ĐH Công Nghệ Thông Tin",
                            Website = "https://uit.edu.vn"
                        },
                        new
                        {
                            Id = 3,
                            DominantType = "Sáng tạo",
                            Major = "Thiết kế đồ họa",
                            UniversityName = "ĐH Mỹ Thuật TP.HCM",
                            Website = "http://hcmufa.edu.vn"
                        },
                        new
                        {
                            Id = 4,
                            DominantType = "Sáng tạo",
                            Major = "Truyền thông đa phương tiện",
                            UniversityName = "ĐH FPT",
                            Website = "https://daihoc.fpt.edu.vn"
                        },
                        new
                        {
                            Id = 5,
                            DominantType = "Xã hội",
                            Major = "Xã hội học",
                            UniversityName = "ĐH Khoa học Xã hội & Nhân văn",
                            Website = "https://hcmussh.edu.vn"
                        },
                        new
                        {
                            Id = 6,
                            DominantType = "Xã hội",
                            Major = "Tâm lý học",
                            UniversityName = "ĐH Sư phạm TP.HCM",
                            Website = "https://hcmue.edu.vn"
                        },
                        new
                        {
                            Id = 7,
                            DominantType = "Quản lý",
                            Major = "Quản trị kinh doanh",
                            UniversityName = "ĐH Kinh tế TP.HCM",
                            Website = "https://ueh.edu.vn"
                        },
                        new
                        {
                            Id = 8,
                            DominantType = "Thực tế",
                            Major = "Nông nghiệp",
                            UniversityName = "ĐH Nông Lâm TP.HCM",
                            Website = "https://hcmuaf.edu.vn"
                        },
                        new
                        {
                            Id = 9,
                            DominantType = "Nghiên cứu",
                            Major = "Khoa học dữ liệu",
                            UniversityName = "ĐH Quốc tế - ĐHQG TP.HCM",
                            Website = "https://hcmiu.edu.vn"
                        });
                });

            modelBuilder.Entity("DACS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DACS.Models.CareerOption", b =>
                {
                    b.HasOne("DACS.Models.CareerQuestion", "CareerQuestion")
                        .WithMany("Options")
                        .HasForeignKey("CareerQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareerQuestion");
                });

            modelBuilder.Entity("DACS.Models.CareerTestResult", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.ChatHistory", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("ChatHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.Feedback", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.PersonalityTest", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("PersonalityTests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.Suggestion", b =>
                {
                    b.HasOne("DACS.Models.User", "User")
                        .WithMany("Suggestions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DACS.Models.CareerQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("DACS.Models.User", b =>
                {
                    b.Navigation("ChatHistories");

                    b.Navigation("Feedbacks");

                    b.Navigation("PersonalityTests");

                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
